<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Epubra.Sample</RootNamespace>
    <AssemblyName>Epubra.Sample</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Epubra.Core\Epubra.Core.csproj" />
    <ProjectReference Include="..\..\src\Epubra.Epub\Epubra.Epub.csproj" />
  </ItemGroup>

</Project>