<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>Epubra.Epub</RootNamespace>
    <AssemblyName>Epubra.Epub</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Epubra.Core\Epubra.Core.csproj" />
  </ItemGroup>

</Project>